# Trust Score Metric Thresholds
ON_TIME_DELIVERY_THRESHOLD = 80
ON_TIME_DELIVERY_HIGH_SCORE = 30
ON_TIME_DELIVERY_LOW_SCORE = 10

QUALITY_RATING_THRESHOLD = 4.0
QUALITY_RATING_HIGH_SCORE = 30
QUALITY_RATING_LOW_SCORE = 10

DEFECT_RATE_THRESHOLD = 5.0
DEFECT_RATE_HIGH_SCORE = 20
DEFECT_RATE_LOW_SCORE = 5

RESPONSE_TIME_THRESHOLD = 24
RESPONSE_TIME_HIGH_SCORE = 20
RESPONSE_TIME_LOW_SCORE = 5

# Trust Level Scores
HIGH_TRUST_THRESHOLD = 80
MEDIUM_TRUST_THRESHOLD = 50

# Trust Level Labels
LABEL_HIGH_TRUST = "High Trust"
LABEL_MEDIUM_TRUST = "Medium Trust"
LABEL_LOW_TRUST = "Low Trust"

# System Defaults
DEFAULT_CSV_PATH = "vendors_20_columns.csv"
DEFAULT_CHART_PATH = "static/chart.png"
